#!/bin/bash

export my_WASSP_HOME="${JD_WORKSPACE}/wassp-repos"
export VXWORKS_DIR="${JD_WORKSPACE}/vx7-integration"
#export VXWORKS_GIT_HOME="http://vxgit.wrs.com/scm/vx7/vxworks.git"
export VXWORKS_GIT_HOME="${JD_WORKSPACE}/vx7-integration/"
export VXWORKS_GIT_BRANCH="vx7-integration"
export my_EZTEST_HOME="${JD_WORKSPACE}/hv-tools/eztest/"
export my_PRODUCT_HOME="${JD_WORKSPACE}/vx7-integration/"

if [[ $PATH != *wassp-repos* ]]; then
    export PATH="${my_WASSP_HOME}/wassp/host/scheduler/bin:${my_WASSP_HOME}/wassp-nest/tools/bin:${PATH}"
fi

# wrpython
export WRPYTHON="${JD_WORKSPACE}/vx7-integration/workbench-4/x86-linux2/bin/wrpython"

# CCR

export CCR="${JD_WORKSPACE}/ccollab-cmdline/ccollabgui"